var a = 10;
var b = 2;
var c = a + b;
var d = a - b;
var e = a * b;
var f = a / b;
var g = a % b;
var h = a++ + 1;
var i = a-- + 1;
var j = a += b;
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(e);
console.log(h);
console.log(i);
console.log(j);
var p = 10;
var q = 20;
var r = 10;
console.log(p == q);
console.log(p == r);
console.log(p != q);
console.log(p != r);
console.log(p > q);
console.log(q > p);
console.log(p >= r);
var m = false;
var n = true;
console.log(a && b);
var num = 16;
var result = (num > 0) ? "True" : "False";
console.log(result);
var message = "welcome to" + "Bizruntime";
console.log("result of string operator is : " + message);
