var isDone = true;
var isnotDone = false;
var tempNum = undefined;
tempNum = null;
var num = null;
var bool = null;
var str = null;
var num1 = undefined;
var bool1 = undefined;
var str1 = undefined;
var val = 'Hello';
val = 123;
val = true;
val = "#$@";
console.log(isDone);
console.log(isnotDone);
console.log(tempNum);
console.log(num);
console.log(num1);
console.log(bool);
console.log(bool1);
console.log(str);
console.log(str1);
