let isDone : Boolean = true;
let isnotDone : Boolean = false;
let tempNum : void = undefined;
    tempNum = null;
let num : number = null;
let bool : Boolean = null;
let str : String = null;
let num1 : number = undefined;
let bool1 : Boolean = undefined;
let str1 : String = undefined;
let val : any = 'Hello';
    val = 123;
    val = true;
    val = "#$@";

console.log(isDone);
console.log(isnotDone);
console.log(tempNum);
console.log(num);
console.log(num1);
console.log(bool);
console.log(bool1);
console.log(str);
console.log(str1);